CREATE TABLE DEPARTMENT(
	deptid		INTEGER	NOT NULL,
	dname		VARCHAR(32) NOT NULL,
	location	VARCHAR(32)	NOT NULL,
	PRIMARY KEY(deptid)
);

CREATE TABLE STUDENT(
	snum	INTEGER		NOT NULL,
	sname	VARCHAR(16)	NOT NULL,
	deptid	INTEGER,
	slevel	VARCHAR(8),
	age		INTEGER,
	PRIMARY KEY (snum),
	FOREIGN KEY (deptid) REFERENCES DEPARTMENT(deptid) ON DELETE SET NULL
);

CREATE TABLE FACULTY(
	fid		INTEGER		NOT NULL,
	fname	VARCHAR(16)	NOT NULL,
	deptid	INTEGER,
	PRIMARY KEY(fid),
	FOREIGN KEY(deptid) REFERENCES DEPARTMENT(deptid) ON DELETE SET NULL
);

CREATE TABLE CLASS(
	cname		VARCHAR(8)	NOT NULL,
	meets_at	DATE,
	room		VARCHAR(8),
	fid			INTEGER,
	PRIMARY KEY(cname),
	FOREIGN KEY(fid) REFERENCES FACULTY(fid) ON DELETE SET NULL
);

CREATE TABLE ENROLLED(
	snum	INTEGER		NOT NULL,
	cname	VARCHAR(8)	NOT NULL,
	FOREIGN KEY(snum) REFERENCES STUDENT(snum) ON DELETE CASCADE,
	FOREIGN KEY(cname) REFERENCES CLASS(cname) ON DELETE CASCADE,
	PRIMARY KEY(snum, cname)
);